// <auto-generated />
namespace Research_science.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dat34 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dat34));
        
        string IMigrationMetadata.Id
        {
            get { return "202404191639061_dat34"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
