// <auto-generated />
namespace Research_science.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class qsss : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(qsss));
        
        string IMigrationMetadata.Id
        {
            get { return "202403221017092_qsss"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
